config/routes.rb
Rails.application.routes.draw do
 # resources :groups
devise_scope :user do
  get 'users/show', to: 'users/registrations#show'
end
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
 # devise_for :users
#  resources :products
  
  get 'products/all(:id)', to: 'products#all'
  post 'products/searching', to: 'products#searching'
  get 'products/:id',      to: 'products#showproductsfromgroup'

  get 'groups/all',   to: 'groups#all'
  get 'groups/alln',   to: 'groups#alln'
  get 'groups/:id',        to: 'groups#showgrp'   

  get 'pharmacies/all(:id)',   to: 'pharmacies#all'

#  post 'makeinv/:invoice',   to: 'makeinv#all'
  post 'makeinv',   to: 'makeinv#all'
  post 'getinvoice',        to: 'getinvoice#showinv'   
  post 'getinvoice/detail',        to: 'getinvoice#showdetailinvoice'   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :products
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def all

    res=[]
    buf={}
    @groups = Group.where('kls_parent=1613').order("NAME ASC").each do |grp|
	    if grp.products.exists?
                buf={}
		buf[:name] = grp.name
		buf[:id] = grp.id
		buf[:kls_parent] = grp.kls_parent
		buf[:kls_unicode] = grp.kls_unicode
		buf[:kls_childcount] = grp.kls_childcount
 	        res.push(buf)
	    end 
    end   
  #  @rgroups = @group
#    @groups = Group.where('kls_parent=1613')
#    render json: @groups
    render json: res

  end

  def alln

    res=[]
    buf={}
    @groups = Group.where('kls_parent=1612').order("name ASC").each do |grp|
	    if grp.products.where("price > 0").exists?
                buf={}
		buf[:name] = grp.name
		buf[:id] = grp.id
		buf[:kls_parent] = grp.kls_parent
		buf[:kls_unicode] = grp.kls_unicode
		buf[:kls_childcount] = grp.kls_childcount
 	        res.push(buf)
	    end 
    end   
  #  @rgroups = @group
#    @groups = Group.where('kls_parent=1613')
#    render json: @groups
    render json: res

  end

  def index
    @groups = Group.all
    render json: @groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def showgrp
    @grp = params[:id].to_s
    @groups=Group.where("kls_parent="+@grp).order("name asc")
    render json: @groups
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>



<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>