config/routes.rb
Rails.application.routes.draw do
 # resources :groups
devise_scope :user do
  get 'users/show', to: 'users/registrations#show'
end
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations' }
 # devise_for :users
#  resources :products
  
  get 'products/all(:id)', to: 'products#all'
  post 'products/searching', to: 'products#searching'
  get 'products/:id',      to: 'products#showproductsfromgroup'

  get 'groups/all',   to: 'groups#all'
  get 'groups/alln',   to: 'groups#alln'
  get 'groups/:id',        to: 'groups#showgrp'   

  get 'pharmacies/all(:id)',   to: 'pharmacies#all'

#  post 'makeinv/:invoice',   to: 'makeinv#all'
  post 'makeinv',   to: 'makeinv#all'
  post 'getinvoice',        to: 'getinvoice#showinv'   
  post 'getinvoice/detail',        to: 'getinvoice#showdetailinvoice'   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :groups
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_filter :verify_authenticity_token

  def showproductsfromgroup

      @grp = params[:id].to_s
      
      g = Group.find_by_id(@grp)
      res=[]
      buf={}
      g.products.where("price > 0").order("name ASC").each do |prod|
	buf={}
	buf[:name] = prod.name
	buf[:id] = prod.id
	buf[:price] = prod.price
	buf[:group_id] = prod.group_id
	res.push(buf)
      end
#      render json: @pr_in_grp
      render json: res

  end

  def all
    
  end

  def searching
     @par = params[:name].to_json
     res = Product.where("to_tsvector('russian',name) @@ to_tsquery('russian',?)",@par)
     if not res.exists?
        res = Product.where('similarity(name,?)>0.1',@par)
     end
     render json: res.order("name ASC")
  end

end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :qtn %>
    <%= f.number_field :qtn %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Qtn</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.qtn %></td>
        <td><%= product.desc %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Qtn:</strong>
  <%= @product.qtn %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @product.desc %>
</p>